### ISSUE TITLE
Composer could not find a composer.json file in /home/runner/work/test-github-action/test-github-action even though composer.json file is present

### ISSUE THREAD

**Issue by premanshup** [chekalsky/phpcs-action#12]
Hello,

I'm getting the below error even when composer.json file is added in the project:

`Composer could not find a composer.json file in /home/runner/work/test-github-action/test-github-action`

https://github.com/premanshup/test-github-action/pull/1

https://github.com/premanshup/test-github-action/runs/1428875407?check_suite_focus=true

Not sure how to resolve this issue, any help will be very much appreciated.

Thank you!

**Comment by chekalsky** [comment]
Hey, I've decided to archive this action as there is a better alternative now available. I've created this action in the very early days of Github Actions and now it's time to go.

[Migration](https://github.com/chekalsky/phpcs-action/blob/master/README.md)
