### ISSUE TITLE
PHP 8 version problem

### ISSUE THREAD

**Issue by tyler36** [chekalsky/phpcs-action#14]
When running in Github Actions, I am getting the following error:

```
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.12. in /github/workspace/vendor/composer/platform_check.php on line 24
```

Is there a config setting I am missing?

**Comment by chekalsky** [comment]
Docker container that this action uses only supports php 7.4. I will look into it, thanks

**Comment by tyler36** [comment]
Thank you for the update.

PS. I think PHP 7.4 support ended 2021-11-28, and security update suport ends 2022-11-28.

**Comment by chekalsky** [comment]
Hey, I've decided to archive this action as there is a better alternative now available. I've created this action in the very early days of Github Actions and now it's time to go.

[Migration](https://github.com/chekalsky/phpcs-action/blob/master/README.md)
